"""Add Module 12 Audit Records

Revision ID: 230b012ccac7
Revises: 5986be0aba6a
Create Date: 2026-09-11 19:51:03.956428
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '230b012ccac7'
down_revision: Union[str, Sequence[str], None] = '5986be0aba6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_did', sa.String(length=500), nullable=True),
    sa.Column('actor_organization_id', sa.UUID(), nullable=True),
    sa.Column('subject_agent_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action_requested', sa.String(length=100), nullable=True),
    sa.Column('authorization_decision', sa.String(length=50), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('policy_id', sa.String(length=100), nullable=True),
    sa.Column('trust_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_records_actor_organization', 'audit_records', ['actor_organization_id'], unique=False)
    op.create_index('ix_audit_records_category_type', 'audit_records', ['event_category', 'event_type'], unique=False)
    op.create_index('ix_audit_records_correlation_id', 'audit_records', ['correlation_id'], unique=False)
    op.create_index('ix_audit_records_occurred_at', 'audit_records', ['occurred_at'], unique=False)
    op.create_index('ix_audit_records_subject_agent', 'audit_records', ['subject_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_records_subject_agent', table_name='audit_records')
    op.drop_index('ix_audit_records_occurred_at', table_name='audit_records')
    op.drop_index('ix_audit_records_correlation_id', table_name='audit_records')
    op.drop_index('ix_audit_records_category_type', table_name='audit_records')
    op.drop_index('ix_audit_records_actor_organization', table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###