"""Add authentication binding fields

Revision ID: 41be6ae53a13
Revises: 230b012ccac7
Create Date: 2026-09-13 12:16:32.995460
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '41be6ae53a13'
down_revision: Union[str, Sequence[str], None] = '230b012ccac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_identities', sa.Column('authentication_issuer', sa.String(length=500), nullable=True))
    op.add_column('organization_identities', sa.Column('authentication_subject', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_organization_identities_authentication_issuer'), 'organization_identities', ['authentication_issuer'], unique=False)
    op.create_index(op.f('ix_organization_identities_authentication_subject'), 'organization_identities', ['authentication_subject'], unique=False)
    
    op.add_column('agent_identities', sa.Column('authentication_issuer', sa.String(length=500), nullable=True))
    op.add_column('agent_identities', sa.Column('authentication_subject', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_agent_identities_authentication_issuer'), 'agent_identities', ['authentication_issuer'], unique=False)
    op.create_index(op.f('ix_agent_identities_authentication_subject'), 'agent_identities', ['authentication_subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_identities_authentication_subject'), table_name='agent_identities')
    op.drop_index(op.f('ix_agent_identities_authentication_issuer'), table_name='agent_identities')
    op.drop_column('agent_identities', 'authentication_subject')
    op.drop_column('agent_identities', 'authentication_issuer')
    
    op.drop_index(op.f('ix_organization_identities_authentication_subject'), table_name='organization_identities')
    op.drop_index(op.f('ix_organization_identities_authentication_issuer'), table_name='organization_identities')
    op.drop_column('organization_identities', 'authentication_subject')
    op.drop_column('organization_identities', 'authentication_issuer')
    # ### end Alembic commands ###