"""Add vc_jwt to VerifiableCredential

Revision ID: 54308e2902f1
Revises: 7a63c62fd265
Create Date: 2026-09-13 22:59:43.308718
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '54308e2902f1'
down_revision: Union[str, Sequence[str], None] = '7a63c62fd265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifiable_credentials', sa.Column('vc_jwt', sa.Text(), nullable=True))
    op.add_column('verifiable_credentials', sa.Column('kid', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifiable_credentials', 'kid')
    op.drop_column('verifiable_credentials', 'vc_jwt')
    # ### end Alembic commands ###