"""Add AgentIdentityKey

Revision ID: 7a63c62fd265
Revises: d2cb4efa8fee
Create Date: 2026-09-13 22:43:54.389575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7a63c62fd265'
down_revision: Union[str, Sequence[str], None] = 'd2cb4efa8fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_identity_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_identity_id', sa.UUID(), nullable=False),
    sa.Column('verification_method', sa.String(length=500), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('key_algorithm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'retired')", name='ck_agent_identity_keys_valid_status'),
    sa.ForeignKeyConstraint(['agent_identity_id'], ['agent_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_method')
    )
    op.create_index(op.f('ix_agent_identity_keys_agent_identity_id'), 'agent_identity_keys', ['agent_identity_id'], unique=False)
    op.create_index(op.f('ix_agent_identity_keys_status'), 'agent_identity_keys', ['status'], unique=False)
    op.create_index('uq_agent_identity_keys_active', 'agent_identity_keys', ['agent_identity_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    
    # --- Custom Data Migration Start ---
    # Copy existing public keys into the new table
    op.execute("""
        INSERT INTO agent_identity_keys (
            id, agent_identity_id, verification_method, public_key, key_algorithm, status, valid_from, created_at
        )
        SELECT 
            gen_random_uuid(), 
            id, 
            did || '#key-1', 
            public_key, 
            key_algorithm, 
            'active', 
            created_at, 
            created_at
        FROM agent_identities
        WHERE public_key IS NOT NULL
    """)
    # --- Custom Data Migration End ---

    op.alter_column('agent_identities', 'public_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agent_identities', 'key_algorithm',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_identities', 'key_algorithm',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('agent_identities', 'public_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('uq_agent_identity_keys_active', table_name='agent_identity_keys', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_agent_identity_keys_status'), table_name='agent_identity_keys')
    op.drop_index(op.f('ix_agent_identity_keys_agent_identity_id'), table_name='agent_identity_keys')
    op.drop_table('agent_identity_keys')
    # ### end Alembic commands ###