"""add_challenge_table

Revision ID: 8e837030c86e
Revises: 54308e2902f1
Create Date: 2026-09-15 16:44:14.541207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8e837030c86e'
down_revision: Union[str, Sequence[str], None] = '54308e2902f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nonce', sa.String(length=100), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_challenges_audience'), 'auth_challenges', ['audience'], unique=False)
    op.create_index(op.f('ix_auth_challenges_expires_at'), 'auth_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_challenges_nonce'), 'auth_challenges', ['nonce'], unique=True)
    op.create_index('ix_auth_challenges_unconsumed', 'auth_challenges', ['audience', 'nonce'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_challenges_unconsumed', table_name='auth_challenges', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_index(op.f('ix_auth_challenges_nonce'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_expires_at'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_audience'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    # ### end Alembic commands ###