"""module16_bitstring_status_list

Revision ID: ac11ca929663
Revises: d2cb4efa8fee
Create Date: 2026-09-16 17:52:13.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac11ca929663'
down_revision: Union[str, None] = 'd2cb4efa8fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitstring_status_lists',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('issuer_did', sa.String(length=500), nullable=False),
    sa.Column('status_purpose', sa.String(length=50), nullable=False),
    sa.Column('bitstring', sa.LargeBinary(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('status_list_vc_jwt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bitstring_status_lists_issuer_did', 'bitstring_status_lists', ['issuer_did'], unique=False)
    op.create_index('ix_bitstring_status_lists_status_purpose', 'bitstring_status_lists', ['status_purpose'], unique=False)
    
    op.add_column('delegations', sa.Column('status_list_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('delegations', sa.Column('status_list_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_delegations_status_list_id'), 'delegations', ['status_list_id'], unique=False)
    op.create_foreign_key(None, 'delegations', 'bitstring_status_lists', ['status_list_id'], ['id'])
    
    op.add_column('verifiable_credentials', sa.Column('status_list_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('verifiable_credentials', sa.Column('status_list_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_verifiable_credentials_status_list_id'), 'verifiable_credentials', ['status_list_id'], unique=False)
    op.create_foreign_key(None, 'verifiable_credentials', 'bitstring_status_lists', ['status_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifiable_credentials', type_='foreignkey')
    op.drop_index(op.f('ix_verifiable_credentials_status_list_id'), table_name='verifiable_credentials')
    op.drop_column('verifiable_credentials', 'status_list_index')
    op.drop_column('verifiable_credentials', 'status_list_id')
    
    op.drop_constraint(None, 'delegations', type_='foreignkey')
    op.drop_index(op.f('ix_delegations_status_list_id'), table_name='delegations')
    op.drop_column('delegations', 'status_list_index')
    op.drop_column('delegations', 'status_list_id')
    
    op.drop_index('ix_bitstring_status_lists_status_purpose', table_name='bitstring_status_lists')
    op.drop_index('ix_bitstring_status_lists_issuer_did', table_name='bitstring_status_lists')
    op.drop_table('bitstring_status_lists')
    # ### end Alembic commands ###